### ISSUE TITLE
How to call create calendar

### ISSUE THREAD

**Issue by g-luo** [AtilaDev/expo-calendar-helper#1]
Where do you call the createCalendar example in the ReadME? When I call it in componentWillMount() or render() I get an error.

**Comment by AtilaDev** [comment]
> Where do you call the createCalendar example in the ReadME? When I call it in componentWillMount() or render() I get an error.

Hi, first you must ask for permission to access calendar on device, then if permission are conceded call newCalendar(). I usually call that method in the moment to create a calendar, but not in the render.
