### ISSUE TITLE
How to set reminder alarm in Android MIUI

### ISSUE THREAD

**Issue by CreateSun** [AtilaDev/expo-calendar-helper#16]
![image](https://github.com/AtilaDev/expo-calendar-helper/assets/47080570/695b7f85-071c-4d69-9cbc-e2a7ccfe4383)
I want my event could auto alarm,  I attempt use property 'alarms' and 'method', but it not useful.

**Comment by AtilaDev** [comment]
This package has been deprecated.
Read the docs, please.
