### ISSUE TITLE
error with _askForCalendarPermissions

### ISSUE THREAD

**Issue by graceluo-intel** [AtilaDev/expo-calendar-helper#2]
Hello, when I try using this API on snack it says that I._askForCalendarPermissions is not a function. (In 'I._askForCalendarPermissions()', 'I._askForCalendarPermissions' is undefined)

**Comment by AtilaDev** [comment]
I haven't tried it in Snack. Anyway, the method is only “askForCalendarPermissions()” without  underscore “_”. The helper is update to sdk33.
