### ISSUE TITLE
createNewCalendar crashes on iOS (no iCloud calendar source)

### ISSUE THREAD

**Issue by jameswilddev** [AtilaDev/expo-calendar-helper#4]
This line assumes that a calendar source called "iCloud" exists.
https://github.com/AtilaDev/expo-calendar-helper/blob/23e652423132753d3d9ecdd9cef64dff1b24f4fe/index.js#L40

On my test device, I don't have one of these.  I have "Gmail", "Other", "Outlook", and a few named after my email addresses.

**Comment by AtilaDev** [comment]
Hi. Sorry for delay. Which version of iOS are you using and is it a real iPhone device or iPhone Simulator?

**Comment by jameswilddev** [comment]
It's a real iPhone running 14.3.  In the end we found that you had to go into the iPhone's settings and enable the iCloud calendar.  In our app we added a pop-up instructing the user to do this if we found the calendar to be missing.

No problems - I was just using this as a reference on how to use Expo's calendar.
